name: build and publish

on:
  push:
    branches:
      - main
    paths-ignore: # do not build for game-irrelvant changes
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '**.md'

jobs:
  build_game:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v3
      - name: update credits
        uses: actions/github-script@v3
        with:
          script: |
            const path = require('path');
            const script = require(path.resolve('.github/workflows/update-credits.js'));
            await script(github, context)
      - name: create env file
        run: |
          touch ${{ github.workspace }}/.env
          echo ${{ secrets.SILENTWOLF_API_KEY }} >> ${{ github.workspace }}/.env
          echo ${{ secrets.SILENTWOLF_GAME_ID }} >> ${{ github.workspace }}/.env
      - name: export with Godot Engine and release on GitHub
        uses: firebelley/godot-export@v4.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload_game:
    runs-on: ubuntu-latest
    environment: production
    name: Publish Game
    needs: [build_game]
    steps:
      - name: download latest HTML5 build
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: 'latest'
          file: HTML5.zip
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: deploy to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: flappy
          ITCH_USER: stewchan
          PACKAGE: HTML5.zip
          VERSION: ${{ steps.download-html.outputs.version }}
